name: CI/CD Pipeline

# Trigger the workflow on push or pull request to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    # Define the operating system to use
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests
    - name: Run tests
      run: npm test -- --watchAll=false

    # Build the project
    - name: Build project
      run: npm run build

    # Optionally, add deployment steps if you want to deploy to a platform like GitHub Pages, Netlify, or Vercel
